format_version: 10
pipelines:
  devpulse-pipeline:
    group: defaultGroup
    materials:
      git-repo:
        git: https://github.com/zelijah11/devpulse.git
        branch: main
    stages:
      - deploy-stage:
          jobs:
            deploy-job:
              tasks:
                - exec:
                    command: docker
                    arguments:
                      - buildx
                      - build
                      - --platform
                      - linux/amd64,linux/arm64
                      - --builder
                      - multiarch
                      - -t
                      - 100.125.202.56:30500/devpulse:latest
                      - --push
                      - .
                - exec:
                    command: kubectl
                    arguments:
                      - apply
                      - -f
                      - devpulse-k8s.yaml
                - exec:
                    command: kubectl
                    arguments:
                      - rollout
                      - restart
                      - deployment/devpulse
